## Questions related to numpy and pandas

### Q1)What is the key difference between NumPy arrays and Pandas Series?
* numpy arrays can have multiple dimensions whereas Pandas series has only one dimension

In [2]:
import numpy as np
import pandas as pd

In [77]:
x=pd.Series([1,2,3,4])
print(x)
x.ndim

0    1
1    2
2    3
3    4
dtype: int64


1

In [13]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)
y.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

### Q2) How would you select the last three elements of a NumPy array?

In [25]:
x=np.array([1,2,3,4])
x[-3:]

array([2, 3, 4])

In [30]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y[1,-3:]

array([6, 7, 8])

### Q3) Explain the purpose of the `DataFrame.groupby()` function in pandas.
* The dataframe groupby function allows us to group the rows togehter on the basis of similar values in a column


In [32]:
df=pd.DataFrame({'student':['A','B','C'],'class':[10,12,10]})
df

student  class
0       A     10
1       B     12
2       C     10

In [37]:
# group the students on the basis of class.
x=df.groupby('class')
# getting list of students in class 10
x.get_group(10)

student  class
0       A     10
2       C     10

### Q4) What is broadcasting in NumPy? Provide an example.
* perfroming arithmetic operations of arrays of diffrent size and dimensions is broadcasting

In [91]:
a= np.array([[1,2,3],[4,5,6]])
a

2

In [93]:
b=np.array([10,20,30])
b

array([10, 20, 30])

In [90]:
# a is 2 dimensional and b is 1 dimensional. broadcasting allows us to add
a+b

array([[11, 22, 33],
       [14, 25, 36]])

### Q5) How can you handle missing or null values in a pandas DataFrame?
* we can handle missing or null values by
    * replacing them with some other value or 0
    * removing them

In [49]:
df1 = pd.DataFrame([1,2,3,4,5],index=['a','b','c','d','e'])
df2 = pd.DataFrame([10,20,30,40,50],index=['c','e','f','g','h'])
df3=df1+df2
df3

0
a   NaN
b   NaN
c  13.0
d   NaN
e  25.0
f   NaN
g   NaN
h   NaN

In [45]:
# removing rows with na
df3.dropna()

0
c  13.0
e  25.0

In [48]:
# replacing na with 0
df3.fillna(0)

0
a   0.0
b   0.0
c  13.0
d   0.0
e  25.0
f   0.0
g   0.0
h   0.0

### Q6) What is the purpose of the `np.random.seed()` function in NumPy?
* it used to generate the same set of random numbers everytime the code runs

In [104]:
np.random.seed(2)
np.random.randint(2,100,5)

array([42, 17, 74, 24, 45])

In [105]:
np.random.seed(2)
np.random.randint(2,100,5)

array([42, 17, 74, 24, 45])

### Q7) Explain the difference between `iloc[]` and `loc[]` in pandas.
* iloc[] uses only index for locating and loc[] uses the label 

In [53]:
df=pd.DataFrame({'student':['A','B','C'],'class':[10,12,10]},index=['a','b','c'])
df

student  class
a       A     10
b       B     12
c       C     10

In [57]:
df.loc['a']

student     A
class      10
Name: a, dtype: object

In [55]:
df.iloc[0]

student     A
class      10
Name: a, dtype: object

### Q8) How would you concatenate two pandas DataFrames vertically?
* we use the concat() function

In [65]:
df1 = pd.DataFrame([1,2])
df2 = pd.DataFrame([10,20,30])
pd.concat([df1,df2], ignore_index=True)

0
0   1
1   2
2  10
3  20
4  30

### Q9) What are the advantages of using pandas over traditional Python data structures like lists and dictionaries?
* pandas allows us to structure our data into tables using dataframes
* dataframes have an index whereas dictionary does not
* lists are one dimentional whereas dataframes are 2 dimensional
* It is easier to alter data in pandas
* we can provide column and row labels using pandas

### Q10) How can you rename a specific column in a pandas DataFrame?
* we can use the rename() function

In [73]:
df=pd.DataFrame({'student':['A','B','C'],'class':[10,12,10]},index=['a','b','c'])
df.rename(columns={'student':'student name'})

student name  class
a            A     10
b            B     12
c            C     10