In [7]:
import numpy as np

In [12]:
# numpy array
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [14]:
#array with only zeroes
arr_z=np.zeros((2,4))
print(arr_z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#array with 1
arr_1=np.ones((3,3))
print(arr_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#empty array
arr_empty=np.empty((2,4))
print(arr_empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# arrange method
arr_arange=np.arange(-10)
print(arr_arange)

arr_arange1=np.arange(10)
print(arr_arange1)

[]
[0 1 2 3 4 5 6 7 8 9]


In [21]:
# changing the shape
arr=np.array([1,2,3,4])
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [24]:
# linspace
lin_space=np.linspace(10,100,10)
print(lin_space)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [31]:
# two-dimensional array
twoD_array = arr.reshape(2, 2)
print(twoD_array)

[[1 2]
 [3 4]]


In [37]:
# three-dimensional array
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [38]:
# displaying the no. of dimensions
print(arr.ndim)
print(threeD_array.ndim)
print(twoD_array.ndim)

1
3
2


In [39]:
# shape of array
print(threeD_array.shape)
print(twoD_array.shape)
print(arr.shape)

(3, 3, 3)
(2, 2)
(4,)


In [40]:
# size of array
print(twoD_array.size)
print(arr.size)
print(threeD_array.size)

4
4
27


### operations 

In [42]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]

In [43]:
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
# converting to array and then adding 
an=np.array(a)
bn=np.array(b)
print(an+bn)

[ 7  9 11 13 15]


In [51]:
print(np.add(4,5))
print(np.add(a,5))

9
[ 6  7  8  9 10]


In [53]:
# comparision operator
c=np.array([34,65,43,21,12,32,13])
print(c[c>4])

[34 65 43 21 12 32 13]


In [56]:
# logical operator 
np.logical_and(threeD_array>10,threeD_array<20)

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True, False],
        [False, False, False],
        [False, False, False]]])

In [58]:
np_trial_data = np.zeros((3, 3))
print(np_trial_data)
print("\n")
trial_data = np_trial_data[:,1:3]
print(trial_data)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [69]:
# printig specifc values
print(threeD_array)
print("\n")
print(threeD_array[2,:,2]) #matrix 2, all rows , 2nd column

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[20 23 26]


In [73]:
# ravel - single line
arr2=np.array([[54,67,43,21,21,356],[35,87,654,33,67,88]])
arr2.ravel()


array([ 54,  67,  43,  21,  21, 356,  35,  87, 654,  33,  67,  88])

In [75]:
# reshape - does not change original array
arr2.reshape((3,4))

array([[ 54,  67,  43,  21],
       [ 21, 356,  35,  87],
       [654,  33,  67,  88]])

In [83]:
# resize - changes original array
arr2.resize(3,4)
print(arr2)


[[ 54  67  43  21]
 [ 21 356  35  87]
 [654  33  67  88]]


In [87]:
# hsplit - splits array
np.hsplit(arr2,4)

[array([[ 54],
        [ 21],
        [654]]),
 array([[ 67],
        [356],
        [ 33]]),
 array([[43],
        [35],
        [67]]),
 array([[21],
        [87],
        [88]])]

In [92]:
#hstack - combines array
print(arr)
print(arr2)
np.hstack((arr,arr))

[1 2 3 4]
[[ 54  67  43  21]
 [ 21 356  35  87]
 [654  33  67  88]]


array([1, 2, 3, 4, 1, 2, 3, 4])

In [2]:
import numpy as np
np_trial_data_1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(np_trial_data_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b  # should be same length

array([ 2,  6, 12, 20])

In [110]:
np_arr_1 = np.array([12,45,8])
var = [2,3,4]  # same length or 1 number
np_arr_1 * var


array([ 24, 135,  32])

In [111]:
np_arr_1*5

array([ 60, 225,  40])

In [97]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [106]:
x=np.array([[1,2,3], [4,5,6], [7,8,9]])
np.linalg.inv(x)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [112]:
# sum of diagonal 
np.trace(x) 

15